#
# Copyright (C) 2015 Niek Linnenbank
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Import('build_env')

env = build_env.Clone()
env.UseLibraries(['libposix', 'libstd', 'libarch', 'libipc',
                  'libfs', 'libexec', 'libapp', 'libruntime' ])
env.UseLibraries(['libstd', 'libapp', 'libarch' ], 'host')

env.UseServers(['core', 'mpiproxy'])

sources = [ 'mpi.cpp' ]

if env['ARCH'] == 'host':
    sources.append('MpiHost.cpp')
else:
    sources.append('MpiTarget.cpp')

env.Library('libmpi', sources)
