#
# Copyright (C) 2009 Coen Bijlsma
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from build import *

#
# Target build
#
env = Prepare(target, [ 'libc', 'libposix' ])
env.Library('libparse', [ 'Parser.cpp', 'StringTokenizer.cpp', 'Delimeter.cpp',
    'CommandLine.cpp', 'URI.cpp', 'URL.cpp', 'FileURL.cpp' ])

#
# Host build
#
env = Prepare(host)
env.Library('host/libparse', [ 'host/Parser.cpp', 'host/StringTokenizer.cpp', 'host/Delimeter.cpp',
    'host/CommandLine.cpp', 'host/URI.cpp', 'host/URL.cpp', 'host/FileURL.cpp' ])
