#
# Copyright (C) 2010 Niek Linnenbank
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Import('build_env')

env = build_env.Clone()
env.Append(CPPPATH = [ '.' ])
env.UseLibraries(['liballoc', 'libc', 'libstd'])
env.UseServers([ 'filesystem', 'process', 'memory', '' ])
env.TargetLibrary('libposix', [ Glob('dirent/*.cpp'),
				Glob('fcntl/*.cpp'),
				Glob('libgen/*.cpp'),
				Glob('sys/*.cpp'),
			        Glob('sys/stat/*.cpp'),
				Glob('sys/utsname/*.cpp'),
			        Glob('sys/wait/*.cpp'),
				Glob('syslog/*.cpp'),
				Glob('time/*.cpp'),
				Glob('unistd/*.cpp'),
				Glob('*.cpp') ])
