#
# Copyright (C) 2009 Niek Linnenbank
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from build import *

env = Prepare(target, [ 'libparse', 'liballoc', 'libposix', 'libexec', 'libc' ],
		      [ 'process', 'memory', 'filesystem' ])
env['LINKFLAGS'] = ' -T kernel/X86/kernel.ld'

env.Program('kernel', [ 'X86/boot.S', 'X86/contextSwitch.S',
			'Kernel.cpp',  'Main.cpp', 'Memory.cpp',
		        'Process.cpp', 'Scheduler.cpp', 'Support.cpp',
			'API/IPCMessage.cpp', 'API/PrivExec.cpp',
			'API/ProcessCtl.cpp', 'API/SystemInfo.cpp',
			'API/VMCopy.cpp',     'API/VMCtl.cpp',
			'X86/Kernel.cpp','X86/Memory.cpp',
			'X86/Process.cpp'  ],
		         LIBS = env['LIBS'], LIBPATH = env['LIBPATH'])
