#
# Copyright (C) 2015 Niek Linnenbank
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Import('build_env')

env = build_env.Clone()
env.Append(CPPDEFINES = { 'private' : 'public', 'protected' : 'public' })
env.UseLibraries([ 'libposix', 'liballoc', 'libstd', 'libtest', 'libexec', 'libarch', 'libipc' ])
env.UseLibraries([ 'libtest', 'libstd', 'libarch' ], 'host')
env.UseServers(['memory'])

# TODO: provide a macro for this? TestProgram() ? or Program override?

env.TargetProgram('BitArrayTest', 'BitArrayTest.cpp')
env.HostProgram('BitArrayTest', 'BitArrayTest.cpp')

env.TargetProgram('ArrayTest', 'ArrayTest.cpp')
env.HostProgram('ArrayTest', 'ArrayTest.cpp')

env.TargetProgram('HashTableTest', 'HashTableTest.cpp')
env.HostProgram('HashTableTest', 'HashTableTest.cpp')

env.TargetProgram('HashIteratorTest', 'HashIteratorTest.cpp')
env.HostProgram('HashIteratorTest', 'HashIteratorTest.cpp')

env.TargetProgram('ListTest', 'ListTest.cpp')
env.HostProgram('ListTest', 'ListTest.cpp')

env.TargetProgram('ListIteratorTest', 'ListIteratorTest.cpp')
env.HostProgram('ListIteratorTest', 'ListIteratorTest.cpp')

env.TargetProgram('StringTest', 'StringTest.cpp')
env.HostProgram('StringTest', 'StringTest.cpp')

env.TargetProgram('SingletonTest', 'SingletonTest.cpp')
env.HostProgram('SingletonTest', 'SingletonTest.cpp')

env.TargetProgram('IndexTest', 'IndexTest.cpp')
env.HostProgram('IndexTest', 'IndexTest.cpp')

env.TargetProgram('VectorTest', 'VectorTest.cpp')
env.HostProgram('VectorTest', 'VectorTest.cpp')

env.TargetProgram('MacrosTest', 'MacrosTest.cpp')
env.HostProgram('MacrosTest', 'MacrosTest.cpp')
