#
# Copyright (C) 2015 Niek Linnenbank
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Import('build_env')

env = build_env.Clone()
env.Append(CPPDEFINES = { 'private' : 'public', 'protected' : 'public' })
env.UseLibraries([ 'libposix', 'liballoc', 'libstd', 'libtest', 'libfs',
                   'libexec', 'libarch', 'libipc', 'libruntime', 'libapp' ])
env.UseLibraries([ 'libtest', 'libstd', 'libarch', 'libapp', 'rt' ], 'host')
env.UseServers(['memory'])

env.TargetHostProgram('BitArrayTest', 'BitArrayTest.cpp')
env.TargetHostProgram('AssertTest', 'AssertTest.cpp')
env.TargetHostProgram('ArrayTest', 'ArrayTest.cpp')
env.TargetHostProgram('HashTableTest', 'HashTableTest.cpp')
env.TargetHostProgram('HashIteratorTest', 'HashIteratorTest.cpp')
env.TargetHostProgram('ListTest', 'ListTest.cpp')
env.TargetHostProgram('ListIteratorTest', 'ListIteratorTest.cpp')
env.TargetHostProgram('StringTest', 'StringTest.cpp')
env.TargetHostProgram('SingletonTest', 'SingletonTest.cpp')
env.TargetHostProgram('IndexTest', 'IndexTest.cpp')
env.TargetHostProgram('VectorTest', 'VectorTest.cpp')
env.TargetHostProgram('MacrosTest', 'MacrosTest.cpp')
env.TargetHostProgram('MemoryBlockTest', 'MemoryBlockTest.cpp')
env.TargetHostProgram('QueueTest', 'QueueTest.cpp')
env.TargetHostProgram('FactoryTest', 'FactoryTest.cpp')
