#
# Copyright (C) 2020 Niek Linnenbank
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

Import('build_env')

env = build_env.Clone()
env.UseLibraries([ 'libposix', 'liballoc', 'libstd', 'libtest', 'libfs',
                   'libexec', 'libarch', 'libipc', 'libruntime', 'libapp' ])
env.UseLibraries([ 'libtest', 'libapp', 'libexec', 'libruntime', 'libipc', 'libarch',
                   'libstd', 'rt' ], 'host')

env.TargetHostProgram('Lz4DecompressorTest', 'Lz4DecompressorTest.cpp')

if env['ARCH'] == 'host':
    env.Depends('Lz4DecompressorTest', '#${BUILDROOT}/etc/Config.h')
    env.Depends('Lz4DecompressorTest', '#${BUILDROOT}/etc/Config.h.lz4')
    env.Depends('Lz4DecompressorTest', '#${BUILDROOT}/boot.img')
    env.Depends('Lz4DecompressorTest', '#${BUILDROOT}/boot.img.lz4')
else:
    env.Depends('Lz4DecompressorTest', '${ROOTFS}/etc/Config.h')
    env.Depends('Lz4DecompressorTest', '${ROOTFS}/etc/Config.h.lz4')
